snikket-im/snikket-server

- docker/Dockerfile
Previously when stopping a container the TERM signal wouldn't reach supervisor, so eventually it is killed.
By directly starting the bash script signals are forwarded and the container is stopped properly.
> Docker: fixed stop signal not reaching process

- docker/entrypoint.sh
Reading untold amounts of data and throwing away all except \~86% seems
wasteful.
This method reads exactly 32 bytes from /dev/urandom, while the previous
method would have stuffed pipes full before finding 32 bytes in the
specified range. All of the entropy of those 32 bytes are also kept in
the base64 form, although this is probably insane overkill.
> Improve efficiency of random secret generation

- docs/advanced/reverse_proxy.md
From the rest of the documentation, I think the domain names in the nginx snippet should be fixed this way.
> Correct some subdomains in nginx reverse proxy documentation

- ansible/files/prosody.cfg.lua
The new portal version will support this (see [1]). The rationale
is also explained over there, but to summarize: If the link ends
in `_` or `-`, some user agents will not linkify it correctly,
worsening the UX.
[1]: https://github.com/snikket-im/snikket-web-portal/issues/48
> Add `/` to invite URL

- docs/advanced/reverse_proxy.md
Apache is still commonly used; the proposed configuration is tested on a setup were port 80 and 443 are used to serve Nextcloud on a vm, and Snikket on another dedicated vm, on one public IP only. The configuration is for Apache 2.4; previous versions may require a `NameVirtualHost *:443` for making SNI to work.
> Add Apache configuration snippet

- ansible/files/prosody.cfg.lua
- ansible/snikket.yml
- ansible/tasks/prosody.yml
This allows exposure of core system metrics (cpu use, memory, c2s connections) to and via the web portal by updating `mod_http_admin_api` and loading `mod_measure_process`.
For more extensive setups, it is now possible to enable Prometheus exposure using an environment variable.
> Improve observability

- docs/advanced/reverse_proxy.md
* Fix HTTP->HTTPS redirect loop by using https on the backend if it is used on the frontend
* Add max body size for HTTP upload
* Add missing "intercept" in sentence
* Whitespace cleanup
Fixes #41.
> Some fixes for the reverse proxy guide

- Dockerfile
```
docker run -it --rm --network host --name tmp --entrypoint bash snikket/snikket-server:beta 
total 17M
drwxr-xr-x 2 _apt root 4.0K May 17 20:36 auxfiles
-rw-r--r-- 1 root root  51K May 17 20:08 deb.debian.org_debian_dists_buster-updates_InRelease
-rw-r--r-- 1 root root  19K Apr 23 13:57 deb.debian.org_debian_dists_buster-updates_main_binary-amd64_Packages.lz4
-rw-r--r-- 1 root root 119K Mar 27 10:05 deb.debian.org_debian_dists_buster_InRelease
-rw-r--r-- 1 root root  17M Mar 27 09:33 deb.debian.org_debian_dists_buster_main_binary-amd64_Packages.lz4
-rw-r----- 1 root root    0 May 17 20:36 lock
-rw-r--r-- 1 root root 7.2K May 17 16:59 packages.prosody.im_debian_dists_buster_InRelease
-rw-r--r-- 1 root root 3.5K May 17 01:30 packages.prosody.im_debian_dists_buster_main_binary-amd64_Packa …
```
> Dockerfile: Remove apt lists at the very end

- Dockerfile
APT leaves some cruft behind, mostly `/etc/python3` and `/etc/python3.7`. These are small but are supposed to be removed.
> Remove some cruft

- ansible/files/bin/create-invite
- ansible/tasks/scripts.yml
1. `qrencode` was not installed
2. the `--qr` flag was not removed after being parsed, so got passed to `prosodyctl` which it doesn't like.
> Fix create-invite --qr

- ansible/files/prosody.cfg.lua
- ansible/tasks/prosody.yml
- docker/entrypoint.sh
Includes migration from mod_http_upload and preserves existing URLs.
Primary benefit for users is likely efficient handling of much larger file uploads.
Testing with Snikket-iOS / Siskin before merging would be good.
> Switch to mod_http_file_share

- docs/advanced/config.md
Went through `prosody.cfg.lua` and the web portal example config. Probably not complete, but should be something which one can point users at.
Fixes #38.
> Add documentation for advanced config options

- ansible/files/prosody.cfg.lua
Both the docs [1] and the code [2] of mod_http_file_share agree that it
should be `http_file_share_size_limit`, not
`http_file_share_file_size_limit`.
[1]: https://prosody.im/doc/modules/mod_http_file_share#larger-files
[2]: https://hg.prosody.im/trunk/file/default/plugins/mod_http_file_share.lua#l35
> Fix incorrect config option

- ansible/files/prosody.cfg.lua
This ensures that users are always able to upload files to the 100MB limit, even if they are encrypted.
> prosody: Add 16 bytes to upload limit to allow for appended GCM tag

- snikket-modules/mod_snikket_restricted_users/mod_snikket_restricted_users.lua
The code was originally written to fail safe in the event of failure, hence
the 'if roles and ...'. However a user with no roles (which is normal for a
normal user, especially on upgrade) can return nil.
Failure is signified by 'false', so now we explicitly catch this and return
early without bypassing isolation. Users with no roles (nil) or with roles
but not prosody:restricted bypass isolation.
> mod_snikket_restricted_users: Don't isolate users with no roles

- ansible/files/prosody.cfg.lua
It appears that, in some environments at least, large file uploads can still
cause a significant increase in RAM. This reduces that effect.
It is expected that a future release will switch to Lua 5.4, which has shown
to have far better GC behaviour.
> prosody: Tune GC to be more aggressive by default

- ansible/files/prosody.cfg.lua
- ansible/snikket.yml
This allows easier verification that you are issuing commands to the right Prosody instance.
> prosody: Show Snikket domain in admin shell prompt

- ansible/files/prosody.cfg.lua
- ansible/snikket.yml
- Forgot to load mod_snikket_restricted_users on the main host (oops), this is now fixed
- Prosody has been updated to kick current sessions when a user's role is modified. This means role changes now take effect immediately, instead of whenever the user happens to reconnect.
> Fix restricted users

- ansible/files/prosody.cfg.lua
- ansible/snikket.yml
- ansible/tasks/prosody.yml
This avoids the app needing to gain logic to opt-in to push notifications.
Such logic may be fragile, and introduce additional traffic and round-trips
that would hurt performance.
Note that this will trigger pushes even to users who only use Android or
non-mobile devices. That should cause no issues, and the impact would be
minor. Also considering that non-iOS devices usually remain online most of the
time anyway.
Not accounted for in this commit is the MUC notification filtering side of
things. By default the MUC will push all messages, and
mod_cloud_notify(_filters) will allow all of them through to the device unless
the user explicitly configures otherwise within the app.
If the server can detect whether a MUC is public or private, it can make the
default behaviour more sensible (maybe …
> prosody: Enable push notifications for offline group members by default

- docs/advanced/reverse_proxy.md
Closes snikket-im/snikket-server#82
Based on snikket-im/snikket-server#87 and discussion in Caddy forums, consolidate information into basic and advanced configuration. The basic set up is easy to use, and only forwards HTTP/S traffic. The advanced set up requires additional plugins, and allows Caddy to be used in place of `sslh` with the added advantage of forwarding port 80 - allowing Snikket to obtain certificates by itself.
> docs: reverse_proxy: Add guide for Caddy

- ansible/files/prosody.cfg.lua
- ansible/tasks/prosody.yml
It was replaced by the circle modules and the configuration was removed in d6b2676829adea15347ca52645f3b9858223047d
This is also in preparation of switching to mod_bookmarks2 / XEP-0402
> prosody: Remove unused mod_default_bookmarks

- ansible/files/prosody.cfg.lua
While these settings themselves are functionally identical, the new one
has additional support from e.g. `prosodyctl check` and also a name not
mentioning "legacy" :)
Requires https://hg.prosody.im/trunk/rev/f254fd16218a or later
> Switch to new Direct TLS setting

- ansible/files/prosody.cfg.lua
- ansible/tasks/prosody.yml
Glorious statistics! RSS is already collected (by `mod_measure_process`), but that need have no relation to actual memory usage in any way, swapped out memory does not count, while unused (by malloc) memory does.. maybe.
> More memory metrics!

- ansible/files/prosody.cfg.lua
This is required for the app to learn of the current registration status (in detail). Without it, the 'push notifications' toggle is always off and disabled.
> prosody: enable muc_registration_include_form

- snikket-modules/mod_update_check/mod_update_check.lua
TXT records can consist of multiple length-prefixed strings, terminated
by a zero-length string, but in most cases there is simply one.
When not using luaunbound, `record.txt` was always the first of those
strings, which should be considered a bug in [dns.lua](https://hg.prosody.im/trunk/file/7a48ccb084dd/net/dns.lua#l608). Prosodys [net.dns](https://hg.prosody.im/trunk/file/7a48ccb084dd/util/dns.lua)
translates it to an array of strings, which means this code tried to
call `match` on an array instead of a string, causing an error. These
arrays have a [metatable](https://hg.prosody.im/trunk/file/7a48ccb084dd/util/dns.lua#l196) with a `__tostring` field set to `table.concat`,
so just passing this string or array trough tostring should always
produce a sensible string.
> mod_update_check: Fix for unbound API difference

- ansible/files/bin/cert-monitor.sh
This is the file that we are waiting for. The cert file might
theoretically be created before the chain, leading to a race condition.
Discovered because I pointed it at directory where I had manually
created only fullchain and privkey.pem
> scripts: Look for chain instead of bare cert

- ansible/files/bin/cert-monitor.sh
- ansible/files/bin/create-invite
- ansible/files/bin/start-coturn.sh
Bash does not appear to be strictly required here, so better to use strict POSIX shell
> scripts: Use stricter POSIX shell

- Dockerfile
- ansible/tasks/prosody.yml
Rationale: The number of lines removed. This is primarily because lua-unbound is packaged so doesn't need to be built from source.
> Update base image to Debian 11

- ansible/files/bin/snikket-turn-addresses
I have that on my test domain and I think this should be a supported
case. In non-APEX cases, that would be a valid way to use the hosting
service.
> turnserver: add support for CNAMEs on the Snikket domain

- ansible/snikket.yml
Bumps prosody-modules for 0f5f2d4475b9, so that the web portal (and XMPP clients) will show imported PEP data immediately, even if Prosody currently has it cached in RAM.
> Fix to support live PEP importing

- snikket-modules/mod_update_check/mod_update_check.lua
mod_update_notify always expects the version to be a number, for comparison
purposes. Here we grab the first valid number we can find from the version
string, which covers all needed cases so far.
> mod_update_check: Always emit a valid number as the version

- ansible/tasks/prosody.yml
So PR #55 was opened back in the Debian 10 "buster" days, before the
switch to Debian 11 "bullseye" and I apparently missed this when bumping
the snapshot date.
> Fix snapshot distribution to Debian 11

- ansible/files/prosody.cfg.lua
This improves memory usage significantly on small servers, as it will now cause uploads over 1MB to use streaming mode or (if streaming unsupported) just reject them.
This may have an impact on large BOSH payloads. For example, if setting a large avatar. However such an avatar is likely too large for the network anyway, and should be reduced by clients before upload.
> prosody: Reduce non-streaming HTTP uploads from 10MB to 1MB

- ansible/files/bin/snikket-turn-addresses
We are transitioning everything to use libunbound, as it is more robust.
Indeed the previous script was failing when a DNS server was unreachable.
libunbound performs CNAME resolution automatically, so that loop has been
dropped.
Finally, a bit more error handling and input checking was sprinkled over
the result. It appears to work!
Thanks to Aerion for reporting the issue, and providing the time and environment to diagnose the cause of the problem.
> snikket-turn-addresses: Update script to use libunbound

- ansible/tasks/prosody.yml
Editing a command with readline is a more of pleasant experience than without.
> prosody: Enable readline support in the Shell

- ansible/files/bin/cert-monitor.sh
- ansible/files/bin/create-invite
If TWEAK domain is set, use it to create invites and in the cert monitor
to import into prosody.
> ansible: Use TWEAK domain if available

- ansible/files/prosody.cfg.lua
- ansible/tasks/prosody.yml
- docs/advanced/config.md
Prosody uses libunbound via luaunbound, which supports DNSSEC but needs
to be pointed at the root zone keys in order to activate it.
Added as a tweak initially since DNSSEC support in resolvers is
currently unknown, so can be enabled by interested users to test and
report back.
> prosody: Add tweak enabling DNSSEC support in resolver

- Dockerfile
- ansible/files/prosody.cfg.lua
- ansible/snikket.yml
- ansible/tasks/prosody.yml
This is two-fold.
Firstly, if Prosody is not running then `prosodyctl shell` should fail there, signaling unhealth.
Secondly, the new [mod_portcheck](https://modules.prosody.im/mod_portcheck.html) reports whether the Prosody in this container instance is listening on the port.
This fixes false positive health checks that would notice that a different Prosody or other XMPP server is listening on port 5280.
Because host networking is used, something listening on port 5280 on the host machine would be visible and stopping Prosody in the container from binding to that port, and possibly others.
This can later be expanded to checking other ports, such as the xmpp-client/5222 and xmpp-server/5269 etc.
**Not tested** because podman doesn't seem to support health checks or does in a way I don't …
> Check health of container via Prosody shell

- ansible/files/prosody.cfg.lua
- snikket-modules/mod_invites_bootstrap/mod_invites_bootstrap.lua
The default invitation expiry of 7 days has been found to be insufficient - people trying to set up instances sometimes do not redeem their initial invite, then come back and find themselves unable to gain access to the instance.
As a special case, this PR extends the validity of bootstrap invites to 28 days by default (it can be tweaked via an environment variable). From a security perspective, I have an aversion to admin credentials with unlimited lifetimes, and so I don't intend to make them never expire (but we can adjust the value based on deployment experience).
Note that bootstrap invitations are not generally used in self-hosted deployments.
Fixes #167.
> Extend bootstrap invite TTL

- ansible/files/bin/snikket-turn-addresses
- ansible/files/prosody.cfg.lua
- ansible/files/supervisord.conf
- ansible/tasks/prosody.yml
#137 broke everything. @horazont identified and corrected serveral problems but there was some sort of performance regression.
After further investigation, the blame was pinned at the extremely aggressive GC settings in https://github.com/snikket-im/snikket-server/commit/e19b0a32afb33df956a1f4ec34d9091a4a48ab8c so this PR reverts that. `threshold = 100` means "start another GC sweep once memory has increased to 100% of what it was at the end of the previous sweep", i.e. at 0% increase in memory use, i.e **all the time**.
@mwild1 suggests reverting to [Prosody's built-in defaults](https://hg.prosody.im/trunk/file/c2616274bef7/util/startup.lua#l17), which is done here via the revert.
> Fix Lua 5.4 performance

- ansible/files/prosody.cfg.lua
Prosody has [happy eyeballs](https://issues.prosody.im/1246) since some time now and it works pretty well.
Question is whether it is now safe to enable IPv6 by default in Snikket as well?  Does any of this even make sense with host networking?
> Remove completed TODO (in Prosody)

- ansible/files/prosody.cfg.lua
- snikket-modules/mod_snikket_restricted_users/mod_snikket_restricted_users.lua
With the newer authz and role stuff in Prosody it is possible to configure permissions various roles should have, and thus a newer version of [mod_isolate_host](https://modules.prosody.im/mod_isolate_host.html) allows turning half of mod_snikket_restricted_users into this one config directive.
Testing needed because the authz permission usage usage in mod_isolate_host is new and there may be edge cases.
> mod_snikket_restricted_users: Replace with config

- ansible/files/prosody.cfg.lua
Since only the web portal uses the password grant internally, and the password grant is considered insecure, it makes sense to enable it explicitly in case it is disabled by default in mod_http_oauth2 at some point.
> Configure OAuth 2 flows

- ansible/files/prosody.cfg.lua
- ansible/snikket.yml
Updates Prosody and modules to 2023-09-19 snapshots.
Adds the `prosody:restricted` role that was renamed `prosody:guest` as part of [changes to user roles in Prosody](https://hg.prosody.im/trunk/rev/082c7d856e61).
https://github.com/snikket-im/snikket-web-portal/pull/158 is also part of this change.
The module changes herein include one that reduces the lifetime of access tokens, restored by https://github.com/snikket-im/snikket-server/pull/180
> Update Prosody and modules inc role changes

- ansible/tasks/prosody.yml
We already install the important packages, namely ca-certificates, lua-readline, lua-unbound but prosody-trunk also recommends luarocks which in turn pulls in Lua 5.1 and Recommends build dependencies such as GCC which inflates the image size.
> Do not install packages Recommended by Prosody to reduce image size

- ansible/files/prosody.cfg.lua
- docs/advanced/config.md
- docs/setup/troubleshooting.md
Option 2
Fixes #56
Mutually exclusive with #183
> Enable IPv6 by default, allowing it to be disabled

- docs/advanced/reverse_proxy.md
Apache2 doesn't need wstunnel mod anymore and officially suggests we use it this way  now.
Even debian stable is compatible with this now.
> Update reverse_proxy.md for new apache2 settings

- ansible/files/services/coturn/finish
If `SNIKKET_TWEAK_TURNSERVER=0` then logs are filled with
> f1b92c3120ff TURN server disabled by environment, not launching.
> f1b92c3120ff TURN server disabled by environment, not launching.
> f1b92c3120ff TURN server disabled by environment, not launching.
> f1b92c3120ff TURN server disabled by environment, not launching.
This tells `s6` not to restart coturn after the `run` script fails to start.
> Tell s6 not to restart coturn when disabled

- ansible/snikket.yml
This version includes a change to mod_tokenauth that periodically clears out expired token grants, to stop them from accumulating.
Related: https://github.com/snikket-im/snikket-web-portal/pull/161
> Update Prosody snapshot

- ansible/files/prosody.cfg.lua
- docs/advanced/config.md
One of the big reasons for having DNSSEC in the first place.
> Use DANE (RFC6698, RFC7673) when DNSSEC is enabled

- ansible/snikket.yml
Fixes #149 
Circles now come with no MUC by default. One or more MUCs can be created for a circle via the web portal (https://github.com/snikket-im/snikket-web-portal/pull/165).
This introduces data format changes which would break on downgrade for circles that have been edited to use this feature.
> Bump prosody-modules for multi-MUC circles

- ansible/files/migrator.cfg.lua
- ansible/files/prosody.cfg.lua
- ansible/tasks/prosody.yml
- docker/entrypoint.sh
- docs/advanced/config.md
Switches to SQLite3 via LuaDBI for storage, including migration.
Fixes #47
> Migrate data to SQLite3

- ansible/files/patches/prosody/modules/prosody-6877786d73d7.patch
- ansible/files/prosody.cfg.lua
- ansible/files/restricted_users.pfw
- ansible/snikket.yml
- ansible/tasks/prosody.yml
- docs/advanced/config.md
This PR brings a bunch of updates for Prosody:
- Password policy enforcement
- Audit logging
- Soft deletion via IBR
- Ability to allow SASL2 auth only
- Remove s2s from share subdomain
- Refactor config using new syntax supported in Prosody
- New restricted user isolation via mod_firewall (preview)
> Prosody config updates Dec 2023

- ansible/files/prosody.cfg.lua
Probably missed because it is in a conditional
> Add another 'Lua' prefix in Prosody config

- ansible/files/prosody.cfg.lua
- ansible/tasks/prosody.yml
This is an experimental XEP, not currently used by the Snikket apps. However it is pretty harmless and we'd like to get more implementation experience. This seems like a good opportunity do to that.
> Enable mod_sasl_ssdp from community modules for XEP-0474 support

- ansible/files/prosody.cfg.lua
OAuth 2 is not meant to be a current Snikket feature and is only used internally. SASL OAUTHBEARER will not work without the certain https endpoints exposed anyway.
Related to https://github.com/snikket-im/snikket-web-proxy/pull/22
> Disable SASL OAUTHBEARER

- docker/entrypoint.sh
- snikket-modules/mod_migrate_snikket_roles/mod_migrate_snikket_roles.lua
Before Snikket 20240109 we used a 'prosody:normal' role for "normal" user accounts in Snikket. From this version we use "prosody:registered" instead. As the default role was updated, this was transparent for most users.
However, some user accounts had the "prosody:normal" role explicitly written to storage, and then it did not get updated to "prosody:registered".
This change migrates any old role names to the new role names on startup.
> Migrate old role names

- snikket-modules/mod_invites_bootstrap/mod_invites_bootstrap.lua
- snikket-modules/mod_snikket_billing/mod_snikket_billing.lua
- snikket-modules/mod_snikket_restricted_users/mod_snikket_restricted_users.lua
- snikket-modules/mod_update_check/mod_update_check.lua
- snikket-modules/mod_update_notify/mod_update_notify.lua
Removes reliance on import name compatibility (`loader.lua` in Prosody)
Ref https://issues.prosody.im/1223
> snikket-modules: Update imports for Prosody namespace change

- Dockerfile
- ansible/files/prosody.cfg.lua
- ansible/tasks/prosody.yml
- snikket-modules/mod_health_report/mod_health_report.lua
- snikket-modules/mod_snikket_version/mod_snikket_version.lua
- snikket-modules/mod_update_check/mod_update_check.lua
This replaces Prosodys `mod_version` with a new `mod_snikket_version`
that retrieves the Snikket version, now stored in a different file, and
advertises it via [XEP-0092](https://xmpp.org/extensions/xep-0092.html).
This also makes Snikket identify itself as `Snikket version stable.yyyymmdd`
instead of `Prosody version Snikket stable.yyyymmdd`.
Overwriting `prosody.version` as done in the `Dockerfile` previously
makes it difficult to determine the Prosody version, which is useful to
know while investigating or debugging issues.
By storing the Snikket version in a different file and reading it once
from this new module, the Prosody version can still be discovered via
`prosodyctl about` and similar.
The version is also made available to some other modules that rely on
the Snikket version, …
> Manage publishing of Snikket version from new module

- ansible/files/prosody.cfg.lua
- ansible/snikket.yml
Uses new feature added in https://hg.prosody.im/trunk/rev/ac60c21015c7
to simplify retrieving the turnserver secret, avoiding one direct usage
of the Lua stdlib
> Simplify config with new read-from-file feature

- ansible/files/prosody.cfg.lua
Mozilla isn't picky and will take our xmpp URI default, but Safari really wants "a URL or mailto:"
https://developer.apple.com/documentation/usernotifications/sending-web-push-notifications-in-web-apps-and-browsers
> Some webpush (such as safari) requires a URL

- ansible/tasks/prosody.yml
After installing the `prosody-trunk` package, the
[`postinst`](https://hg.prosody.im/debian-trunk/file/97a741185e4f/prosody-trunk.postinst)
script generates a certificate and corresponding private key for
`localhost`. For regular installs this might be useful to ensure that at
least one certificate exists to populate Prosodys certificate discovery
mechanism, possibly to serve as a default certificate when no other
hostname included in the TLS SNI extension. Since the container image is
built once, these get distributed along with it, which is not desirable.
Noticed by a user in July 2024
> Delete localhost cert created by package postinst script

- CHANGELOG.md
- README.md
- docs/advanced/config.md
- docs/setup/troubleshooting.md
- docs/setup/upgrading.md
Seems people have a recent enough Docker to have the [new command](https://docs.docker.com/compose/migrate/) but are missing the old, which causes confusion.
> Update docs for compose v2

- ansible/files/prosody.cfg.lua
- ansible/snikket.yml
No longer required to include the "code" response type when registering
a password-grant-only client.
To go with https://github.com/snikket-im/snikket-web-portal/pull/202
> Update prosody-modules snapshot for mod_http_oauth2 improvements

- ansible/files/prosody.cfg.lua
When the TURN server is disabled with `SNIKKET_TWEAK_TURNSERVER=0` the
following error is logged on startup:
```
b87e815b742b snikket.example.org:turn_external  error  Failed to initialize: the 'turn_external_secret' option is not set in your configuration
```
This silences the error by only loading mod_turn_external when the TURN
server is enabled.
> Silence failure to initialize mod_turn_external when coturn disabled
