ansible/tasks/prosody.yml
- Fix room destruction of circle rooms when circle is deleted or fails to be created (fixes #17)
- Add circle rooms to bookmarks of (newly added) members (fixes #16)
=> Import fixes from prosody-modules

docs/advanced/reverse_proxy.md
Typo fixed and added a note on SNI-based proxying.
=> Updated reverse_proxy.md Apace section.

Dockerfile
https://pythonclock.org/
Includes #50 (merge that first?)
=> Switch Ansible to Python 3, remove Python 2

ansible/files/bin/start-coturn.sh, ansible/files/turnserver.conf, docs/advanced/firewall.md
Fixes #32; see there and in the text for details and rationale.
=> Make TURN server port range configurable

ansible/tasks/prosody.yml
So that it stays the same even if the URL is changed.
Suggested in https://github.com/snikket-im/snikket-server/pull/55#pullrequestreview-724415212
=> Specify a filename for repository

ansible/files/prosody.cfg.lua, ansible/snikket.yml, ansible/tasks/prosody.yml, snikket-modules/mod_snikket_restricted_users/mod_snikket_restricted_users.lua
This implements all the restrictions listed in https://github.com/snikket-im/snikket-server/issues/37#issuecomment-911331262
Fixes #37
=> Restrictions for restricted users

docs/advanced/reverse_proxy.md
The more common setup for apache2 will be the same as for ngnix.
Have apache2 on the same machine as snikket. This is the working config for that.
=> Update reverse_proxy.md with apache2 "normal" mode

ansible/files/bin/cert-monitor.sh, ansible/files/bin/start-coturn.sh, ansible/files/prosody.cfg.lua, ansible/snikket.yml, ansible/tasks/prosody.yml
Partner to https://github.com/snikket-im/snikket-web-portal/pull/110
=> Feature: account import/export (Prosody side)

docs/setup/quickstart.md, docs/setup/troubleshooting.md, docs/setup/upgrading.md
Vast majority of this text contributed by Jonas.
=> docs: Document issue with libseccomp2 in Debian buster

docs/advanced/reverse_proxy.md
Based on https://prosody.im/doc/websocket
Not tested
=> docs: Add reverse proxy settings for BOSH and WebSockets

ansible/snikket.yml, docker/entrypoint.sh, snikket-modules/mod_snikket_restricted_users/mod_snikket_restricted_users.lua
This includes a whole lot of authz and token auth changes.
Should go along with updates to snikket-web-portal
=> Update Prosody and modules to latest

ansible/tasks/prosody.yml
Lua 5.4 has much better memory usage and garbage collection characteristics.
Did we check whether all Lua components are 5.4-ready?
=> Switch to Lua 5.4

ansible/files/prosody.cfg.lua, ansible/tasks/prosody.yml
This module is included with Prosody and should be mostly equivalent.
=> Switch to mod_turn_external for STUN/TURN

docs/advanced/reverse_proxy.md
Just removed useless lines and simplified setup.
Specified the use of websockets
=> Small update for apache2 reverse proxy

ansible/files/prosody.cfg.lua
=> Fix incorrect option name for mod_http_file_share

Dockerfile, ansible/snikket.yml, ansible/tasks/coturn.yml, ansible/tasks/prosody.yml
=> Switch to Debian 12 as base image

ansible/files/prosody.cfg.lua, ansible/tasks/prosody.yml
- Disable PLAIN
- Enable SASL2, Bind 2, FAST
=> Authentication improvements

ansible/files/prosody.cfg.lua, ansible/tasks/prosody.yml
This was the Plan all along, right?
=> Enable mod_client_management

ansible/files/prosody.cfg.lua, ansible/tasks/prosody.yml, docs/advanced/config.md, snikket-modules/mod_snikket_deprecate_general_muc/mod_snikket_deprecate_general_muc.lua
=> Remove deprecated features (welcome, general MUC)

ansible/files/prosody.cfg.lua
I keep forgetting how these things are connected, hopefully this helps next time.
=> Clarify how federation restrictions work

docs/advanced/dns.md
Update it, so it only explains how to add xmpps over port 443, and not about changing ports 5222 5269, because snikket doesn't do that anyway.
=> Update dns.md, deleting options you can't change anyway

ansible/snikket.yml
Upates Prosody to [852a61c720d0](https://hg.prosody.im/trunk/rev/852a61c720d0)
This includes [fixes](https://hg.prosody.im/trunk/rev/852a61c720d0) for token [expiry](https://hg.prosody.im/trunk/rev/ddfe07041fc5) and [DANE](https://hg.prosody.im/trunk/rev/7264c4d16072) improvements
=> Update Prosody snapshot

ansible/snikket.yml
This fixes various issues affecting circle chats (see #211 for details).
=> Bump prosody-modules to 791aa8072f58 for groups fixes

ansible/snikket.yml
Fixes snikket-im/snikket-web-portal#171
=> Bump prosody-modules for commit f76909ec1300

ansible/snikket.yml
Latest mod_push2 requires fairly new trunk
=> Update prosody and modules, especially for push2
